#!/bin/bash
rsync -ru /usr/share/nginx/html/django/static/blog/ personalpage/blog/static/blog/ --stats --dry-run | grep -q 'Number of regular files transferred: 0'
FILES_TRNSFD_COUNT=$?

if [[ "$FILES_TRNSFD_COUNT" == "0" ]]; then
  exit 0
else
  echo "-----------------------------------"
  echo "Pre-commit hook failed             "
  echo "  - Static iles are out of sync    "
  echo "-----------------------------------"
  echo
  echo "Make sure you sync any uploaded data!"
  echo "Hint:"
  echo
  echo "rsync -ru /usr/share/nginx/html/django/static/blog/ personalpage/blog/static/blog/"
  exit 1
fi
