# Generated by Django 2.1.5 on 2019-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('init_date', models.DateTimeField(verbose_name='Account Established Date')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_handle', models.CharField(max_length=15)),
                ('post_text', models.CharField(max_length=1000)),
                ('post_date', models.DateTimeField(verbose_name='Date Posted')),
            ],
        ),
    ]
