# Generated by Django 2.1.5 on 2019-01-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190117_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_handle',
            new_name='author_id',
        ),
    ]
