# Generated by Django 2.1.5 on 2019-01-17 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190117_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='handle',
            field=models.CharField(default='na', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
