# Generated by Django 2.1.5 on 2019-01-17 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190117_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default=datetime.datetime(2019, 1, 17, 20, 32, 53, 192040, tzinfo=utc),
            max_length=50, unique=False),
            preserve_default=False,
        ),
    ]
