# Generated by Django 2.1.5 on 2019-02-12 18:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190117_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
