# Generated by Django 2.1.5 on 2019-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190220_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default='Bio coming soon.', max_length=1000),
        ),
    ]
